import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Vikings from './Vikings'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Vikings</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Vikings</h1>

                <div className={styles.vikings}>
                    <Vikings />
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href='https://github.com/mlodygbelmondo'
                    className={styles.footerHeader}
                >
                    Piotr Kaczorowski
                </a>

                <a
                    href='https://www.flaticon.com/authors/freepik'
                    title='freepik'
                >
                    Sword, spear, unknown, axe icons created by Freepik -
                    Flaticon
                </a>
            </footer>
        </div>
    )
}
