import {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import { fetchVikings } from "../lib/vikings";
import styles from "../styles/Home.module.css";
import Vikings from "./Vikings";

export const getServerSideProps: GetServerSideProps = async () => {
  const vikings = fetchVikings();
  return {
    props: {
      vikings,
    },
  };
};

const Home: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ vikings }) => (
  <div className={styles.container}>
    <Head>
      <title>Vikings</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>Vikings</h1>

      <div className={styles.vikings}>
        <Vikings vikings={vikings} />
      </div>
    </main>
    <footer className={styles.footer}>
      <a
        href="https://github.com/mlodygbelmondo"
        className={styles.footerHeader}
      >
        Piotr Kaczorowski
      </a>

      <a href="https://www.flaticon.com/authors/freepik" title="freepik">
        Sword, spear, unknown, axe icons created by Freepik - Flaticon
      </a>
    </footer>
  </div>
);

export default Home;
